1
# list1=[612]
# list2=[123]
# new_list=[]
# def plus(list1,list2):
 
#  length=min(len)(list1),len(list2)
#  for i in range(length):
#   qosh=list1[i]+list2[i]
#   new_list.append(qosh)
#  return new_list

# print(new_list)


2
# list=["123"]
# def num(tek):
#     for i in tek:
#      if len(list[1])==len(list[3]):
#       return "true" 
# k=num(list)     
# print(k)    
6
# list=[9,2,7,1,8]
# def quick_sort(list_a):
#     length=len(list_a)
#     if length<1:
#         return list_a
#     else:
#         a=list_a.pop()
#         b=[]
#         c=[]
#         for i in list_a:
#             if a>i:
#                 b.append(i)
#             else:
#                 c.append(i)

#     return quick_sort[b]+[a]+quick_sort[c]
# print(quick_sort(list))    

       